### ISSUE TITLE
Error when trying to load schematic

### ISSUE THREAD

**Issue by doitliketyler** [boy0001/FastAsyncWorldedit#1137]
**Debug paste link**:
https://hastebin.com/tuwedekuva

**Description of the problem:**
When trying to load a schematic chat says:
There wase an error handling a FAWE command: [See console]
java.lang.UnsupportedOperationException: TODO FIXME

And the console says:
https://pastebin.com/XHqvkUUq

**How to replicate**:
Type this command: //schem load [schematicName]

**Comment by datitisev** [comment]
Same here. Only happens for me with Spigot 1.13.1.

I think it's because FAWE looks for `v1_13_R1` and because we are using Bukkit `v1_13_R2` (latest version of Spigot for example) it thinks the version is unsupported. See https://github.com/boy0001/FastAsyncWorldedit/blob/master/bukkit/src/main/java/com/boydti/fawe/bukkit/FaweBukkit.java

**Comment by TheBentoBox** [comment]
I can confirm this. I'm not allowed to save schematics using the `SCHEMATIC` format at all and I can't load anything in the `SPONGE_SCHEMATIC` format even though it's the only one I can save in. So basically I can't use schematics I save with FAWE I can only load/paste schematics I created with normal non-FAWE WorldEdit.

**Comment by IronApollo** [comment]
Unable to reproduce with the description OP gave. Schematic I use is "grass.schem".
https://gyazo.com/cf3dc12854ffb101ff2065f88c97741c
