### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#129]
For testing purpose I gave myself the `*` permission.
This seems to bypass the limits set in the `config.yml` which is expected as `*` includes `fawe.bypass`.

Then I added `-fawe.bypass` to myself to see if this persists.
The first thing I noticed was that regenerating after selection a region far bigger than the currently allowed 20 mio blocks did not give me an error message like "selection too big", it just responded that the action was successful.
However no block changes happened at all.

Then I selected a few blocks and tried to `//set stone` there. This was cancelled because I was supposedly `outside allowed region`. There were no block changes, but FAWE responded immediately after the first message that the `action completed in 0.051 seconds`.

As conclusion it seems for me that `fawe.bypass` does not bypass WorldEDIT restrictions rather WorldGUARD restrictions.

Not sure if we have issues here or just a misapprehension.

FAWE 3.5.0-ba2f915

**Comment by boy0001** [comment]
> Then I added -fawe.bypass to myself to see if this persists.
The first thing I noticed was that regenerating after selection a region far bigger than the currently allowed 20 mio blocks did not give me an error message like "selection too big", it just responded that the action was successful.

I haven't fully recoded the regen command, just some hacky solution to have it async/respect region restrictions. Since regen doesn't go through the EditSession it doesn't respect any of the limits. Additionally regenerating a chunk internally isn't a block change. 

> As conclusion it seems for me that fawe.bypass does not bypass WorldEDIT restrictions rather WorldGUARD restrictions.

`fawe.admin` will ignore the limits in the config and `fawe.bypass` shouldn't be set with `*`

**Comment by Janmm14** [comment]
> ```fawe.bypass``` shouldn't be set with ```*```

That might depend on the used permissions plugin.

**Comment by RoboMWM** [comment]
> That might depend on the used permissions plugin.

Indeed it does. PEX does a "hacky" way of obtaining all permissions with this, and often breaks plugins that define their own wildcard permissions.
