### ISSUE TITLE
max-blockstates should include pistons

### ISSUE THREAD

**Issue by SecretlyJealous** [boy0001/FastAsyncWorldedit#1311]
```
# Blockstates include Banner, Beacon, BrewingStand, Chest, CommandBlock, 
    # CreatureSpawner, Dispenser, Dropper, EndGateway, Furnace, Hopper, Jukebox, 
    # NoteBlock, Sign, Skull, Structure
    max-blockstates: 0
```
This config option prevents players from essentially creating a large amount of blockstates in a chunk to crash the server however recently I had a player who was able to exploit this with pistons. They would create a bunch of pistons using `//br sphere #clipboard 5`. There are probably other commands that can also be used to achieve this through worldedit but this is the main one I know about. It would be nice if pistons were included in this blockstates config option to prevent this:

![Untitled](https://user-images.githubusercontent.com/10485646/58754248-f545eb00-84c3-11e9-89d0-c4de64873e4e.png)

![Untitled](https://user-images.githubusercontent.com/10485646/58754264-448c1b80-84c4-11e9-8ee5-0a0777ddbee3.png)

![Untitled](https://user-images.githubusercontent.com/10485646/58754284-9634a600-84c4-11e9-9092-6fc331f00f77.png)

**Comment by N0tMyFaultOG** [comment]
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.
