### ISSUE TITLE
Huge lag issues

### ISSUE THREAD

**Issue by Victhetiger** [boy0001/FastAsyncWorldedit#143]
Hi,

I've recently tested your plugin on my Skyblock server and I've ran into the following issues:

- When restarting the island the first time, everything is fine, tps goes back up to normal (20). But when I restart the island once again, the tps goes down to 18 and doesn't go back up to 20 until I restart. If I restart the island one more time, it goes to 16 and never goes back up, always removing 2 ticks a second for some reasons.
- I was wondering if PaperSpigot wasn't compatible with FAWE?

Also, the water spawns as some kind of block instead of flowing water.

Using: Version 3.5.0-c1b22fb of FAWE and Paperspigot 1.9.4

Thank you

**Comment by boy0001** [comment]
Please do a timings so I can see what's affected it.

**Comment by Victhetiger** [comment]
Here you go: https://timings.aikar.co/v2/?id=3d51a5696f2a482a9098dd8b3f9291bd

Thank you for the quick reply, I really needed this.

**Comment by boy0001** [comment]
Okay, it's uSkyBlock doing stuff that appears the be the issue. It may take me a while to debug this given that's it's no within FAWE.

**Comment by Victhetiger** [comment]
Alright, thank you very much.

**Comment by boy0001** [comment]
Can't replicate any TPS drop. Getting a 32ms spike when resetting the island since uSkyblock is pasting the schematic on the main thread. This is entirely normal.
https://timings.spigotmc.org/?url=17049927

Without FAWE getting a muich larger spike:
https://timings.spigotmc.org/?url=17049868
Neither produces any long term TPS drop for me.

Are you able to show me on your server?

**Comment by Victhetiger** [comment]
Yes, the IP is atmos.me. I'll be on there.
