### ISSUE TITLE
Feature Request: Stable API with semantic versioning

### ISSUE THREAD

**Issue by rlf** [boy0001/FastAsyncWorldedit#146]
Just trying to code against the FaweAPI, and already found some major problems with regard to compatibility.

If I test for FAWE v3.5.0, I currently need to figure out whether it's a 3.5.0-0bc703e (latest stable) or 3.5.0-b209c62 (latest pre-release), since the signature for how to get hold of an EditSession differs between the two.
```java
// 3.5.0-stable
EditSession session = new FaweAPI().getNewEditSession(world);
// 3.5.0-dev
EditSession session = FaweAPI.getNewEditSession(world);
```

Maintaining compatibility to this sort of API is very difficult.
Please consider a simple/uniform way to get hold of the API, and consider using strict semantic versioning of said API, so we have a chance of detecting functional compatibilities (without having to rely heavily on reflection).

**Comment by boy0001** [comment]
```Java
EditSession session = FaweAPI.getNewEditSession(world);
```
Is what you should be using. 

I bumped the version in a43cef7b2da7f84e4763760a50af09baf038fba3 if you want to check if it's greater than 3.5.0

```Java
Plugin fawePlugin = Bukkit.getPluginManager().getPlugin("FastAsyncWorldEdit");
String[] split = fawePlugin.getDescription().getVersion().split("-")[0].split("\\.");
int[] version = new int[]{Integer.parseInt(split[0]), Integer.parseInt(split[1]), Integer.parseInt(split[2])};
if (checkVersion(version, 3, 5, 1)) {
  // FAWE 3.5.1 or greater
}

public static boolean checkVersion(final int[] version, final int major, final int minor, final int minor2) {
    return (version[0] > major) || ((version[0] == major) && (version[1] > minor)) || ((version[0] == major) && (version[1] == minor) && (version[2] >= minor2));
}
```

**Comment by boy0001** [comment]
Update: New version system contains the following information (assuming a correctly compiled jar)
 - Date
 - Shortened commit hash
 - Build number

Since it's in the format: `year.month.day-hash-build`, the above code should still work for checking if it's above `3.5.0`. 

The version object can also be obtained using `Fawe.get().getVersion()`

**Comment by rlf** [comment]
For what is good and holy.
What the freaking flying bejeebiz have you done reg. "semantic versioning" of your API?

Is this what we have available now??
http://ci.athion.net/job/FastAsyncWorldEdit/ws/mvn/com/boydti/fawe-api/

Please read up on what "semantic versioning" means - and please - oh please - consider maintaining your versioning of (at least) your API using semantic (or some resemblence of this) versioning

**Comment by boy0001** [comment]
Uh, have I broken anything I'm unaware of?

**Comment by rlf** [comment]
You haven't broken anything, but you have made the peeps using your API unable to gauge the difference between versions.

Say you have v3.5.2 of your API.
When I include that in my code, I know that it will work with that version.

When you release v3.5.3 - I know (if it's semantically correct), that my code will still work - since the move only bumped the micro-part of the version, meaning it was a "stability" update, which didn't change on the methods I already use.

If you release v3.6.0 - My version will still work, but there might be some new way of doing stuff (minor version means methods/features added).

And finally, when you release v4.0.1 - I know I probably have to bump the version and re-compile, since the major version changed, the new version will not be fully backward compatible.

What we have now, is `year.month.day-hash-buildnumber` which says nothing about the severity of the update, or whether it's a "release version" or a "pre-release" or simply a dev-release from jenkins.

**Comment by boy0001** [comment]
I don't have releases

**Comment by rlf** [comment]
In a semantic-versioning-world, you would have a 1.0-SNAPSHOT release (the builds available of your API)

**Comment by boy0001** [comment]
> Say you have v3.5.2 of your API.
When I include that in my code, I know that it will work with that version.

Say I have `16.09.21-b2ef1cb-294` when you include that in your code, it will also work with that version.

> If you release v3.6.0 - My version will still work, but there might be some new way of doing stuff (minor version means methods/features added).

It might still work, but there's no such guarantee. The difference between a major, minor and patch is subjective. If you are going by any change that has even a 1% chance to break some hypothetical code is major, then I'd literally be bumping the major version number each commit.

> And finally, when you release v4.0.1 - I know I probably have to bump the version and re-compile, since the major version changed, the new version will not be fully backward compatible.

Again, no such guarantee. A major change will not always break the API you are using. If you want to know what's been changed, read the changelog.

> In a semantic-versioning-world, you would have a 1.0-SNAPSHOT release (the builds available of your API)

Because 1.0-SNAPSHOT for every jar is totally more informative than `year.month.day-hash-buildnumber`.

**Comment by rlf** [comment]
The difference between major, minor and micro is NOT subjective - when using semantic versioning.
That is the beauty of it.

**Comment by boy0001** [comment]
Adding a single method to a class or interface could be a "major" change. Maybe you add a method when doing a bug fix or when adding a minor feature.

If the class is public and non-final, it could be considered part of the API, and if something were to extend it, adding a method would break compatibility. So a minor bug fix or feature is thus a major breaking change. 

Except you probably don't consider adding a single method a major breaking change because otherwise (let me quote myself from earlier):
> If you are going by any change that has even a 1% chance to break some hypothetical code is major, then I'd literally be bumping the major version number each commit.

Anywho, I noticed you don't even follow semver yourself, given that you release updates which aren't even backwards compatible, and then just bump the patch number. 
> When updating to the v2.7.1, the conversion is MANDATORY and cant be reversed.
MAKE SURE TO BACK UP BEFORE USING THIS BUILD.

So I'll just stick with my current inadequate versioning scheme thanks.

**Comment by rlf** [comment]
My API follows semantic versioning - and the API is backwards compatible.
Data conversion and API compatibility is not the same thing.

But I hear you, you are angry that I point out your current versioning scheme causes problems for integrators, and I'm sorry you feel that way.

But it doesn't make me less right.

Your current versioning scheme depends on 3 things, the date it was "published", the "hash-code" of the change and the build-number of your build-server.

Those 3 things have nothing to do with the actual version of your software.
I.e. if you make a new build of the exact same code, on a different day, or even on the same day, you will get different version-strings.

If you (correctly), claim you have still not released a version, having ONE version number is even better than what you have now.

That is why I suggest using v1.0-SNAPSHOT (Mavens way of saying "code changes, use the latest at all times"), or even 3.5.1-DEV.

I know that in the flux of making a lot of changes, maintaining a semantic version is a pain, but the reason you make an API is, to "promise" integrators some sort of "stable" interface, and to at least give them a chance to react to changes (by maintaining the versioning of said API).

If you don't do that, then why have an API in the first place?

**Comment by boy0001** [comment]
> My API follows semantic versioning - and the API is backwards compatible.
Data conversion and API compatibility is not the same thing.

Except you are meant to at least bump the minor version when adding features, so you don't follow semver.

> But I hear you, you are angry that I point out your current versioning scheme causes problems for integrators, and I'm sorry you feel that way. But it doesn't make me less right.

It also doesn't make you less wrong. Counterpoint, it's just you, not "integrators" (singular plural), and it doesn't cause "problems", as you correctly pointed out:
> You haven't broken anything

> Your current versioning scheme depends on 3 things, the date it was "published", the "hash-code" of the change and the build-number of your build-server. Those 32 things have nothing to do with the actual version of your software.

Really, because I would have thought that the date of the commit, the hash of the commit, and the index of the commit have a lot to do with the it. All three should be the same regardless of where or when you compile the code. Yes, the build number happens to be in sync with the build server, however it is the offset commit index.

> If you (correctly), claim you have still not released a version, having ONE version number is even better than what you have now.

Having one version number for every version has absolutely no information. Try debugging software when you have a bug report with that information. I'd rather have the date, hash and build thanks.

> I know that in the flux of making a lot of changes, maintaining a semantic version is a pain, but the reason you make an API is, to "promise" integrators some sort of "stable" interface, and to at least give them a chance to react to changes (by maintaining the versioning of said API).

The stability of said API is totally independent of what I choose to call that version. I also call bullshit on your ability to know what's changed simply by looking at the version number without checking the changelog or code. 

> If you don't do that, then why have an API in the first place?

You can't be serious...

Anywho, you'll be pleased to know that the new jars use semver (as an addition to the existing, and vastly superior versioning scheme). It's automated by the build script with no input on my end.

**Comment by rlf** [comment]
Nice!
Unless, ofc. you still require us to "depend" on a specific build from your buildserver.

No need to get personal, just trying to educate you reg. semantic versioning, and the benefits of it (esp. reg. APIs and integrators).

If you don't have the Zen to learn, don't.

**Comment by boy0001** [comment]
I was already aware of semver, and am still of the opinion it's pretty meaningless.

You can depend on a specific version or the [latest](http://ci.athion.net/job/FastAsyncWorldEdit/ws/mvn/com/boydti/fawe-api/latest/). Or like, compile it yourself if that's what you want? I thought we already established that it would output the same version regardless of where you compile it?

**Comment by rlf** [comment]
If you are aware of semver, and think it's meaningless, you fail to understand the point.

But, hey, I don't want to waste more time on this - I am not going to make you understand this way anyway. So, what-ever, do your thing.

**Comment by boy0001** [comment]
It's a moot point given that I already added semantic versioning for you.
