### ISSUE TITLE
Cannot get regions to work.

### ISSUE THREAD

**Issue by nikitis** [boy0001/FastAsyncWorldedit#150]
So i gave my default group worldedit.*

I gave him fawe.preciousstones

I create a preciousstones region.  
I try to edit 3 blocks using a selection inside the precious stones region.

ERROR:
I get blocked by FAWE stating "Your WorldEdit action was cancelled:  No allowed region.  Action completed in 0.047 seconds.

Is this broken?  Or am I configuring it incorrectly?

Thanks for your time.

**Comment by nikitis** [comment]
I'm using 1.10 spigot, 3.5.1-110 build #123 of FAWE.  and WE 6.1.3 Snapshot.  Latest development build PreciousStones.

**Comment by CleanerOrc** [comment]
Probably not the answer, but Were your feet located INSIDE the region?  Far as I understand, your feet have to be inside a region that you have access to modify, in order to use WE thru FAWE. 

I found that out when I created a 1 block high WorldGuard region and was standing on top of it, but I kept getting the not in region error when I tried to WE on selections in the region.

**Comment by nikitis** [comment]
Yes I was in a 41x41x81 region in the middle of it.  There is no way I was
not in the region.

**Comment by nikitis** [comment]
Issue still exists as of build 159,  FastAsyncWorldEdit-bukkit110-3.5.1-f202a56.jar  

I also tried using a default PreciousStones config and same results.

**Comment by nikitis** [comment]
Issue still present in build #168.  You posted his was corrected in #166, but this is not the case for me.

**Comment by boy0001** [comment]
Fixed
