### ISSUE TITLE
World.regenerate(Region) doesn't respect region

### ISSUE THREAD

**Issue by rlf** [boy0001/FastAsyncWorldedit#157]
In uSkyBlock we use WE to handle non-chunk-aligned island-regions, esp. when clearing the islands.

We use chunk-regeneration (because it's blazingly fast), and then we use WE for the "border-regions".

Unfortunately, FAWE crashes the server under certain conditions, and doesn't seem to respect the region as WE used to do.

In WE it seems, the part of the chunk NOT to be regenerated is copied, then the whole chunk is generated, and finally the "missing part" is pasted (just from the top of my head).

This is not done when using FAWE.

**Comment by boy0001** [comment]
Very vague. What conditions does it crash under? Do you have a crash report? What is FAWE doing instead? 

Also chunk generation is a lot slower than block placement using FAWE.

**Comment by boy0001** [comment]
Oh, it should be noted that world regeneration doesn't occur through the EditSession, and is entirely implementation specific, so how you obtain the world object is important. FAWE has a wrapper class which contains optimizations, regions restrictions, limit checks and async handling.

See `PlayerWrapper` and `WorldWrapper` here:
https://github.com/boy0001/FastAsyncWorldedit/tree/master/core/src/main/java/com/boydti/fawe/wrappers.

Latest version of FAWE will return a wrapped world object if you use EditSession#getWorld()

Also since FAWE has limited control over world generation code, there aren't much optimizations it can do there. It is much faster changing blocks normally.

**Comment by rlf** [comment]
We did a lot of testing using WE and AWE with regard to "clearing a region", and there the world-regen out-performed setting all blocks to AIR.

The problem lies when we have to regenerate (re-create what our WorldChunkGenerator has made), esp. in nether (where it isn't just AIR, but rather the chunk-generation logic we want).

The issue here mentions the crashes, but isn't about those, it's about the world.regenerate(region) that doesn't respect the region when using FAWE (but does without).

**Comment by Janmm14** [comment]
Whicb world's regenerate? The wrapped one of the one gained through bukkit?

**Comment by rlf** [comment]
Let me try to make a test-scenario, and describe it for you.

**Comment by Janmm14** [comment]
Not for me, I'm just commenting here but are not involved in fawe development.

**Comment by boy0001** [comment]
Assumed fixed?

**Comment by rlf** [comment]
Sorry, got side tracked, not fixed last I tested it - but let me retry on the latest.

**Comment by rlf** [comment]
Fixed in the latest version
