### ISSUE TITLE
CoreProtect not logging changes

### ISSUE THREAD

**Issue by acidbyt3** [boy0001/FastAsyncWorldedit#159]
Not sure if this is intended/normal behaviour but CoreProtect isn't logging any block changes.
I tried both with and without CoreProtect or CoreProtectLogger under "allowed-plugins:"

**Comment by RoboMWM** [comment]
Either enable WE logging in CoreProtect or install Blockshub

**Comment by acidbyt3** [comment]
It's enabled, it logged WE before installing FAWE.
`# Logs changes made via the plugin "WorldEdit" if it's in use on your server.
worldedit: true`

**Comment by RoboMWM** [comment]
Might also want to check the API access thingy or whatever. CoreProtect logs FAWE for me (though I'm very slowly transitioning away from CoreProtect)

**Comment by boy0001** [comment]
You need to use BlocksHub. The default CoreProtect logger won't work from async threads.

**Comment by acidbyt3** [comment]
Thanks for the clarification and suggestion. :) 
I looked into it - from what I can tell, BlocksHub is an add-on to be used alongside CoreProtect and not a replacement, correct? Because replacing CoreProtect would not be practical for me.

**Comment by tancou** [comment]
I am running a 1.9.4 paperspigot
BlocksHub.jar v1.2
BlocksHub-CoreProtect.jar v1.2.1
Last version of FastAsyncWorldedit (FastAsyncWorldEdit-bukkit19-3.5.1-4c59ffc.jar)
Worldedit (worldedit-bukkit-6.1.2.jar)
Coreprotect v2.12.0

Blocksub config :
```
BlocksHub:
  version: 2
  worlds:
    - world3
    - *
```
My world is named world3

Coreprotect config :
`worldedit: true`

FastAsyncWorldedit config :+1: 
```
extent:
  allowed-plugins:
  - CoreProtect
  debug: true
```

Coreprotect doesn't log my copy paste.
I tried to recompile BlocksHub Sources (main and Coreprotect) with a spigot 1.9.4 configuration, it doesn't change anything.

If anyone here has managed to log copy paste into Coreprotect, can you post your configuration?
Thanks in advance.

**Comment by Nayrisian** [comment]
I would like to comment that in your BlocksHub configuration, your worlds has " - * " in it. This does not follow how the system works, you may have confused it with how the permissions works (Using wildcards).

Instead, it uses RegEx to capture names of the worlds you define by the expression.
You should instead put " - .* " instead. The period acts as a placeholder for RegEx, where as the asterisk acts as a condition for none, one or many. (I would personally use .+ just because .* is redundant, you cannot have a world with a blank name.. I think?)

This will most likely not fix your main issue though, but this might fix some weird issues with people's BlockHub configuration hopefully if they come across this.

**Comment by N0tMyFaultOG** [comment]
If the issues persists still, reopen the ticket.

**Comment by soshimee** [comment]
I saw all of the above and tried all of the above, but I still get the issue.
