### ISSUE TITLE
[BUG] CoreProtect is a "potentially inefficient WorldEdit extent" 

### ISSUE THREAD

**Issue by xBreaksx** [boy0001/FastAsyncWorldedit#167]
Hi,

So recently I've been having errors pop up in console whenever I'm using WorldEdit saying that there's this plugin that is apparently a "potentially inefficient WorldEdit extent", which is CoreProtect.

Though there is the BlocksHub plugin that my server should rather be using instead, CoreProtect still does its job pretty well, even though it's very "outdated" and "abandoned."

Anyways, it also tells me "For area restrictions, it is recommended to use the FaweAPI" and then "To allow this plugin add it to the FAWE `allowed-plugins` list", but there is no 'allowed-plugins' list in the FAWE config, and the configuration wiki page shows nothing of this, either.

Thanks for the help m8s :)

**Comment by Janmm14** [comment]
Try simply adding that option.

**Comment by boy0001** [comment]
Don't add the option, FAWE is disabling the CoreProtect logger because it's slow and it will throw errors  when used from an async thread. If you want logging use BlocksHub, or the inbuilt FAWE logging.

Also FAWE is intentionally disabling the CoreProtect logger because otherwise it inserts it and performs checks on each block change regardless of whether it is disabled in the config. If you don't want to see this message, get the CoreProtect devs to fix their plugin, or set `debug: false` in the FAWE config.

**Comment by xBreaksx** [comment]
@boy0001 So what about the BlocksHub-CoreProtect integration? Would that work?

**Comment by boy0001** [comment]
@xBreaksx yes
