### ISSUE TITLE
Block end_gateway not works

### ISSUE THREAD

**Issue by haelexuis** [boy0001/FastAsyncWorldedit#199]
I use latest version. Block with ID 209 not works, if I type '//set 209' or '//set end_gateway' then happend this 
![image](https://cloud.githubusercontent.com/assets/9253908/17086897/b93e607a-51fd-11e6-833f-489483cde167.png)
(no texture, only effects). Without FAWE it works.

**Comment by mibby** [comment]
@boy0001 I can also confirm this occurs for me. 

FastAsync dev 185
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

Normal worldedit + AWE, setting end_gateway works perfectly fine.

**Comment by boy0001** [comment]
Probably need end_gateway:2 or something

**Comment by mibby** [comment]
But why would that be needed? Normally ```//set 209``` works fine without FAWE, both stock WE and WE + AWE. :o

**Comment by boy0001** [comment]
Because setting a block through the bukkit api, like WE and AWE do, it corrects the data, whereas doing it with NMS I need to handle it myself. 

As for the reason why 0 doesn't work, the data indicates direction, so up,down,n,e,s,w = 0,1,2,3,4,5,6. Up and down aren't valid directions for end_gateway.

**Comment by mibby** [comment]
Ah, gotcha. So basically needs to detect a facing direction and correct the data with FAWE to match WE functionality. :P

**Comment by boy0001** [comment]
Oh, nevermind, seems to be something else.

**Comment by mibby** [comment]
Any ideas what it may be?

**Comment by boy0001** [comment]
Merging with #320
