### ISSUE TITLE
Pasting schematics (Stairs, Chunks of random blocks)

### ISSUE THREAD

**Issue by C1audi0** [boy0001/FastAsyncWorldedit#201]
When pasting a schematic, sometimes weird chunks of block appear like a rectangle of stone or grass. Also when pasting stairs sometimes they face the wrong way, other then that it pastes the schem pretty quick. Awesome plugin.

**Comment by RoboMWM** [comment]
> sometimes weird chunks of block appear like a rectangle of stone or grass

FAWE probably skipped a couple chunks due to memory or w/e issues(?). Wish there were a way to have it attempt to repaste these a little later or something though. Just a guess though because idk what you mean by "rectangle of stone or grass," as if it were a perfect rectangle or just something akin to that.

> Also when pasting stairs sometimes they face the wrong way

More details on this would be appreciated. Are they all facing a certain direction (and what direction/orientation)? Does it happen with new schematics? etc.

Also you should include your /version and /version fastasyncworldedit output here.

**Comment by dordsor21** [comment]
latest FAWE version - getting the problem with all stairs in all schematics pasted. Quite an important issue.

**Comment by C1audi0** [comment]
I'm not sure what version was the issue with the stairs, but I waited a bit and saw there was an update, I'm now on version 16.08.15-fb33ecf-210 and stairs work just fine now. Running worldedit version 6.1.3;7a097ca , and running version Paper Spigot 1.10.2-R0.1 . This if off topic though, when you're going to '//set' something, you could do '//set test' and it will do air, not a big deal but sometimes people put the wrong ID or name for a block and they think its broken, when it's their fault.

**Comment by dordsor21** [comment]
using build 214

**Comment by dordsor21** [comment]
All datavalues of blocks are reset to 0 i.e. 1:4 -> 1:0

**Comment by dordsor21** [comment]
I also receive the issue when //flip'ing stairs.

**Comment by boy0001** [comment]
Still an issue?

**Comment by dordsor21** [comment]
No, if it's been a problem, it's been fixed. Many duplicate issues posted and closed concurrently with this one
