### ISSUE TITLE
Suggestion - History limit / max logs option for use-disk.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#219]
Would it be possible to implement a history limit for the use-disk functionality? WorldEdit normally has a setting to limit history size to avoid everything being cached at once - to avoid filling up all the free memory. 

```
history:
    size: 10
    expiration: 10
```

So what if someone would like to write history to disk to save on memory usage even more but would also prefer to avoid high disk space usage with heavy worldedit use? With the default compression settings, the history file for a relatively large schematic paste (~700kb schematic) was over 7MB on testing. Even if history was set to delete after a single day, a lot of disk space could potentially be used up if there are a lot of operations. I think having a setting to set the maximum history in the order operations were last made would be great to avoid any potential for abuse. 

Defaulting to unlimited history for full rollback support with the option to limit maximum logs per player and delete after x days, and using the worldedit history size setting if using cache instead of disk.

_Note: I have not tested if the WorldEdit history size works with FAWE. But I am making the assumption that it does for cache, doesn't for disk - as that makes the most sense logically and functionally for rollback support by default._

**Comment by mibby** [comment]
Alternatively; it wouldn't be much of a problem if the history file for a single operation wasn't 7MB. Not sure if that is bugged or if the default compression is really crappy. I'd rather avoid raising the compression strength to keep CPU usage low - to avoid TPS spikes / lag. Unless the expense is really insignificant.

All about trying to keep FAWE as fast as possible. :P

**Comment by Janmm14** [comment]
I'd say sql database is not faster, at the end sql also saves the data to disk.

**Comment by mibby** [comment]
A local SQL database connection wouldn't be faster than disk with querying, indexing, and multithreading compared to flat file? It saves to disk either way, but perhaps it would be significantly less space used depending on how the data and tables are written / arranged?

**Comment by boy0001** [comment]
The schematic will probably always be better compressed since it is fixed sized, whilst history needs to support random locations and random size (though not always the case since I'm using a different compression algorithm). 

Default should be less than 9 bytes per block. You can probably increase it to level 3, before it starts getting noticeably slower from the compression. (Mostly depends on whether compression is faster than the disk bottleneck)
> I have not tested if the WorldEdit history size works with FAWE. But I am making the assumption that it does for cache, doesn't for disk

Yeah, disk only gets removed at startup based on age, not after a time limit. Anywho, good idea, I'll implement it soon, though it'll be disabled by default.

>  I'd rather avoid raising the compression strength to keep CPU usage low - to avoid TPS spikes.
It should all be done async, TPS shouldn't be impacted? It is expensive, however on a multi-core CPU it shouldn't impact the main thread, and just result in increasing delays to worldedit operations.

> Maybe logging to an SQL database would be faster and smaller?
Definitely not
 - Usually no compression (the table compression in MySQL is too weak to even compensate for the increased overhead of table indexing and other overhead)
 - Much slower writes (upwards limit of about 60K inserts/second), compared to millions.

SQL database is currently going to be used to index the files, but not for storing individual blocks.

**Comment by mibby** [comment]
Thanks for the info dump. I'll look into raising the compression level to 3 and running some more large paste tests. 

In any case, a maximum size limit to disk history might be a nice thing to implement in the future similar to the cache history (assuming it is functional). :)

**Comment by boy0001** [comment]
Untested. The history should be limited by the player's `MAX_HISTORY_MB` limit.
