### ISSUE TITLE
WorldEdit operations do not copy NBT data of some entities

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#347]
WorldEdit copy/paste/schematic operations do not copy NBT data of entities. Such as an armorstand that is invisible in a build. When copying and pasting to a new area or loading a schematic of the build, the armorstand reappears. Is preserving the NBT data something that should be done?

**Comment by boy0001** [comment]
Can't replicate. Latest FAWE with Spigot 1.10:
http://i.imgur.com/i3aR4f8.png (Armor stand is invisible and carrying visible armor, copied fine)

**Comment by mibby** [comment]
To be more specific, I copied an area that has a hologram. Holograms use an invisible armorstand to display the text as a nametag. When I pasted the area, a vanilla (no nbt) armorstand appeared in the place of where the hologram should have been.

**Comment by boy0001** [comment]
@mibby 
There's no reason why the hologram plugin needs to use NBT if it has a custom entity extending ArmorStand and gets the information from a database instead.

**Comment by mibby** [comment]
So you are saying the custom entity is being copied and falling back to a standard armorstand on paste?

**Comment by boy0001** [comment]
WorldEdit copies entities by getting the id (ArmorStand) and nbt. Everything else is ignored since you can't really copy it when you don't know what kind of information to expect. It's just a limitation of how WorldEdit copies entities, and there's probably nothing I can do without adding a dependency for whatever hologram plugin you use.
