### ISSUE TITLE
Allow MemoryOptimizedClipboard to have block set to air

### ISSUE THREAD

**Issue by filoghost** [boy0001/FastAsyncWorldedit#51]
https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/object/clipboard/MemoryOptimizedClipboard.java#L64-L65

These two lines are causing the following code to fail:
`schematic.setBlock(currentPoint, new BaseBlock(BlockID.AIR))`

It's impossible to change a block to air in a schematic before pasting it. I haven't checked if there are other occurencies of similar behaviour. Normal WorldEdit alone works fine.

**Comment by boy0001** [comment]
I'm not sure if that's the issue. The default behavior has the block as air if it's null:
https://github.com/sk89q/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/BlockArrayClipboard.java#L122-L133

So as long as you don't set the same location twice, it should work?

**Comment by filoghost** [comment]
But that is the method to obtain the block, not to set it. I'm not setting it twice, but the clipboard was loaded from disk. Anyway it should be fixed now, thanks.

**Comment by boy0001** [comment]
The clipboard is just a holder of information, it can be backed by whatever data structure I choose. For example, the DiskOptimizedClipboard uses a RandomAccessFile to store the information instead of a byte array. What's important is that getting the block at the location in the clipboard returns the value that you set. 

The fix I pushed only changes the behavior to account for setting the id at a location twice, it doesn't create a new array at the index if there wasn't one already there. My point being that it can be redundant to set it to air when the default return value is air.

**Comment by filoghost** [comment]
Yes it's redundant to set air when the default value is air, but the code doesn't appear to check if the original value is really air. I was having problems changing a solid block to air.
