### ISSUE TITLE
Client crash when i paste a schematics.

### ISSUE THREAD

**Issue by theocerdan** [boy0001/FastAsyncWorldedit#563]
**Debug paste link**:
https://hastebin.com/gaqiwehahe

**Description of the problem:**
Hello, I have big problem, when I paste a schematics on my server in versions 1.7.10, lot of player crashs but no error in the console just client side (http://i.imgur.com/qFhjl9e.png & http://i.imgur.com/lHZbLDD.png).

**How to replicate**:
1) Start a server with spigot 1.7.10
2) Paste a schematics (http://i.imgur.com/BvGnhVM.png)
3) If you don't crash try to repaste this

**Version**:
FAWE version: http://i.imgur.com/2xev2VD.png
Server version: http://i.imgur.com/SUqOrLe.png
Client version : 1.7.10

thx

**Comment by Fewness** [comment]
yes patch this please

**Comment by theocerdan** [comment]
Ok new update, so even with a // set 0 this crash

**Comment by TheKayaba** [comment]
Having this issue as well.

**Comment by dordsor21** [comment]
are you all on 1.7.10 also?

**Comment by TheKayaba** [comment]
Yes I am on 1.7.10 as well.

**Comment by Gabik21MC** [comment]
I can confirm this, also using 1.7.10

**Comment by Gabik21MC** [comment]
Any news on this?

**Comment by theocerdan** [comment]
Yes pls fix this

**Comment by boy0001** [comment]
I can't replicate. Can someone attach a schematic which is known to cause this?

**Comment by Gabik21MC** [comment]
I tried some stuff out. It only happens if there are 2 or more players in view distance of the edit. It is enough to make a cuboid of 4x4x4 (or even smaller) or just do //fixlightning and after 1-6 edits one (or both) players get kicked for the reason mentioned above (image from OP http://i.imgur.com/qFhjl9e.png). I have a build server where 4 players build on a map and they told me that it appears on every single worldedit action (of every type), if they're near each other.

**Comment by Gabik21MC** [comment]
@boy0001 I don't want to annoy you, but could you just confirm that you've read my message, ty :)

**Comment by Gabik21MC** [comment]
bump
