### ISSUE TITLE
Request: SQL logging

### ISSUE THREAD

**Issue by krusic22** [boy0001/FastAsyncWorldedit#630]
Can you add SQL support for history and clipboard logging?
Not really important but a nice thing to have. :)

**Comment by boy0001** [comment]
I think it would be good to discuss what you want to achieve out of this. 

SQL isn't a particularly good for storing this kind of binary data, which is why the `summary.db` only stores a summary of the files on disk. 
 - If the server stops unexpectedly (crash?), a partial file can be undone, whereas an sql insert wouldn't have gone through. 
 - FAWE needs to read/write randomly to the clipboard, which can't be done in SQL (efficiently) - so a temporary file or in memory storage would be needed anyway
 - MySQL & SQLite have poor performance for large binary files (>100kb afaik)

**Comment by krusic22** [comment]
Maybe SQL isn't such a good idea :D
My main problem isn't disk usage or space just that there are way too many files created (my history has 200 files under 10kb and most of them are 7 days old).
Maybe just a option to store old history files on SQL or somehow compress them or even just delete them automatically?

**Comment by boy0001** [comment]
They are deleted automatically.

**Comment by krusic22** [comment]
Just going to close this since I don't see a use for it now.
Thanks :D
