### ISSUE TITLE
Keep entities while pasting

### ISSUE THREAD

**Issue by joeywp** [boy0001/FastAsyncWorldedit#708]
When pasting a schematic, it deletes all the entities currently residing in the pasted area. Is there a way to keep these entities that already existed in the pasted area before pasting a schematic when using the API specified here?

https://github.com/boy0001/FastAsyncWorldedit/wiki/Pasting-a-schematic

**Comment by dordsor21** [comment]
Are these animal entities etc and item frames/armour stands etc? Because if these are kept, it's very likely you'll have entities that end up inside blocks, which could cause client-side lag (if you've got a lot that you can't find to remove) or require a pass-over to delete entities that are only within blocks, which isn't really fun.

**Comment by boy0001** [comment]
It will only remove the entity if a block is placed there. You can add a mask to the EditSession to not set an air block if there is already air there.
