### ISSUE TITLE
Region Protection Issue

### ISSUE THREAD

**Issue by Kirrasio** [boy0001/FastAsyncWorldedit#821]
# Bug report

**Debug paste link**:

https://hastebin.com/ezacoqidec
**Description of the problem:**

It's not allowing anyone to world edit even with the correct permission nodes
**How to replicate**:

Turn on region restrictions, I have permission set. Tested with residence and worldguard.

**Checklist**:

- [/] I included a `/fawe debugpaste` link
- [/] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [/] I made sure I am using an up-to-date version of FAWE
- [/] I Made sure the bug/error is not caused by any other plugin

**Comment by braceyourself07** [comment]
Since you are using LuckPerms try using `/lp verbose true ` and see if any nodes are coming up as undefined/false when trying to use worldedit that gets restricted.  Keep in mind that any players online will also trigger the verbose permissions output.  So you may want to do this on a test server alone to minimize extraneous reports.

**Comment by Kirrasio** [comment]
fawe.bypass is coming up as false and fawe.residence is coming up as true. If I enable that bypass they can we over other peoples residences.
