### ISSUE TITLE
[Enhancement] Block Alias .yml

### ISSUE THREAD

**Issue by RealmportalMC** [boy0001/FastAsyncWorldedit#958]
A YML to allow for custom names for blocks.
so i could change 1:0 to be "stone" or "rock"
"//set rock" would be equivalent to "//set stone"

**Comment by dordsor21** [comment]
likely useful but sort of in reverse for when 1.13 comes

**Comment by RealmportalMC** [comment]
ah, you could do it both ways i guess,

**Comment by boy0001** [comment]
Okay, so how about a `patterns.yml` and `masks.yml`. In it you can define custom patterns/masks using either a combination of existing patterns, expressions, or craftscripts.

The format will be `<keyword> <pattern|craftscript>`, using `%s0 %s1` as arguments. e.g.
`#sim #simplex[%s1][%s2]` would allow using `#sim` instead of `#simplex`. 
`rock stone` would add the alias.

And for a craftscript example:
// TODO after I work out the implementation details.

**Comment by RealmportalMC** [comment]
Great idea :D. sorry about the late response. but that sounds pretty much perfect

**Comment by RealmportalMC** [comment]
Im also thinking of it being a list. all 4 of the names below would be valid for QUARTZ_BLOCK

you'd also need a check and maybe backup and reset the alias.yml if duplictate items are found

alias:
  QUARTZ_BLOCK:
  - 155
  - quartz
  - quartzblock
